Updated Chapters 2/3/4 with corrections
IntelliTect/EssentialCSharp pull request #181
Opened 2021-06-09 18:30 UTC by kNoAPP

Errata: Added log of significant changes.
2.15: Added public identifiers to correct Reflection error.
2.17: Added a space in code to match book.
3.9/10/11/12/20/21/27/28: Replaced "Pascal" with "Visual Basic" to match book.
3.27: Removed whitespace for the additional example. 
4.18: Code comments for incrementing example were incorrect. They've been updated to match the book.
Program: Added "Listing" to Regex because it confused Listing.cs files with Table.cs files causing Listings 4.4/7.3/etc. to fail.

2021-06-10 19:10 UTC, BenjaminMichaelis requested changes
Some good changes here! Thank you! It looks like some of the tests need to be updated is the most pressing problem I see currently, as 3 tests are failing, but one looks like the content might of still be incorrect even after a change (4.02, I left comments on these). If you would be willing to update these tests that would be awesome, otherwise I don't mind making the changes needed and pushing them to your branch if you would like.

2021-06-10 19:10 UTC, BenjaminMichaelis commented on src/Chapter03/Listing03.27.Slicing.cs
> +                "C++", "TypeScript", "Visual Basic",
Would you be willing to update the test [Chapter3.27 Test](https://github.com/IntelliTect/EssentialCSharp/blob/various-additional-fixes/src/Chapter03.Tests/Listing03.27.Slicing.cs) or allow me to correct it?

2021-06-10 19:10 UTC, BenjaminMichaelis commented on src/Chapter03/Listing03.28.AdditionalArrayMethods.cs
> +                "C++", "TypeScript", "Visual Basic",
Would you be willing to update the test [Chapter3.38 Test](https://github.com/IntelliTect/EssentialCSharp/blob/various-additional-fixes/src/Chapter03.Tests/Listing03.38.ReversingAString.cs) which also needs the file to be renamed to "Listing03.28.ReversingAString.cs" or allow me to correct it?

2021-06-10 19:10 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.02.Negative.cs
> +            decimal debt = -28382607800141.79M;
I don't see this as being the correct number in the book for this listing? It looks like to me that the correct number should be "-26457079712930.80M"

2021-07-08 23:13 UTC, BenjaminMichaelis commented
@kNoAPP I just wanted to follow up and see if you wanted to update this with the changes or if I should start work on it otherwise! 
Thanks!

2021-07-10 00:40 UTC, kNoAPP commented
You can start work on it! Sorry for the super late reply.

2021-12-20 02:09 UTC, merged