Switched from cs to XML on csproj files
IntelliTect/EssentialCSharp pull request #388
Opened 2022-11-02 18:38 UTC by MarkMichaelis

These files are not used as project files, just sample files that are listed in the chapter.

2022-11-02 23:25 UTC, Keboo approved these changes

2022-11-03 04:06 UTC, BenjaminMichaelis requested changes

2022-11-03 04:06 UTC, BenjaminMichaelis commented on src/Chapter03/Listing03.03.EnablingNullableProjectWide.xml
> -#region INCLUDE
We can't not have regions, but it can be an xml file

2022-11-03 21:53 UTC, BenjaminMichaelis approved these changes

2022-11-03 22:57 UTC, merged