Code Completed for Chapter 4 Technical Review
IntelliTect/EssentialCSharp pull request #397
Opened 2022-11-12 21:38 UTC by MarkMichaelis

2022-11-14 18:46 UTC, BenjaminMichaelis commented
Does this supersede #396

2022-11-14 18:49 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.22.NestedIf.cs
> +            // Check 1.
```suggestion
            // Condition 1.
```

nit: keep verbiage the same throughout listing

2022-11-14 19:06 UTC, BenjaminMichaelis requested changes

2022-11-14 19:06 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.22.NestedIf.cs
> +// Justification: Checkihng for null isn't discussed yet.
```suggestion
// Justification: Checking for null isn't discussed yet.
```

2022-11-14 19:06 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.22.NestedIf.cs
> +            // Check 1.
```suggestion
            // Condition 1.
```

nit: keep verbiage the same throughout listing

2022-11-14 19:06 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.38.NullConditionalOperator.cs
> +            if (length is not null && length != 0)
isn't length not null here? Removing the necessity of the following two not null checks and int being nullable?

2022-11-14 19:06 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.20.ConstantInterpolatedStrings.cs
> +#pragma warning disable IDE0059 // Unnecessary assignment of a value
I feel like I keep seeing a lot of unnecessary suppressions, like here I don't think I see anything we don't use. And I think there's other cases of this as well that I'd look at.

2022-11-14 19:06 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.49.InputValidation.cs
>                    + "Push ENTER to quit");
```suggestion
                  $"{ Environment.NewLine }ERROR:  Enter a value from 1-9. "
                  + "Push ENTER to quit");
```
can we use environment.newline over \n here?

2022-11-14 19:06 UTC, BenjaminMichaelis commented on src/Chapter04/Listing04.50.SwitchStatement.cs
>                      "\nERROR:  Enter a value from 1-9. "
```suggestion
                    $"{ Environment.NewLine }ERROR:  Enter a value from 1-9. "
```
And here

2022-11-14 19:06 UTC, BenjaminMichaelis commented on src/Chapter04/Table04.04.CheckForNull.cs
> +                // null.
Github actions seems to suggest that the error message is "The given expression is always of the provided ('object') type", is maybe this error message slightly off?

2022-11-14 23:29 UTC, MarkMichaelis commented on src/Chapter04/Listing04.38.NullConditionalOperator.cs
> +            if (length is not null && length != 0)
No, `length` would be null here if `segments` is null.

2022-11-16 06:16 UTC, BenjaminMichaelis approved these changes

2022-11-18 00:51 UTC, Keboo approved these changes

2022-11-18 00:55 UTC, merged